name: ebml
description: An RFC 8749 compliant Extensible Binary Meta Language parser.
version: 1.0.0
repository: https://github.com/abitofevrything/dart_ebml
topics: [ebml, codec]

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.18.0
  petitparser: ^6.0.1
  xml: ^6.4.2

dev_dependencies:
  http: ^1.1.0
  lints: ^2.1.0
  test: ^1.24.0
